ATMOSPHERE_LIBRARIES := libmesosphere libstratosphere libexosphere

TOPTARGETS := all clean

$(TOPTARGETS): $(ATMOSPHERE_LIBRARIES)

$(ATMOSPHERE_LIBRARIES):
	$(MAKE) -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(ATMOSPHERE_LIBRARIES)