name: Bug Report
description: Something doesn't work correctly in Atmosphère.
title: "[BUG] "
body:
- type: markdown
  attributes:
    value: |
      Note: If the bug or crash you encountered is related to
      - software used to make "backups"
      - software explicitly distributed for piracy, etc.
      
      then contributors will not provide support for your issue and your issue will be closed.
- type: textarea
  attributes:
    label: What's the issue you encountered?
    description: |
      Describe the issue in detail and what you were doing beforehand.
      Did you make any changes related to Atmosphère itself?
      If so, make sure to include details relating to what exactly you changed.
  validations:
    required: true
- type: textarea
  attributes:
    label: How can the issue be reproduced?
    description: Include a detailed step by step process for recreating your issue.
  validations:
    required: true
- type: textarea
  attributes:
    label: Crash Report
    description: |
      Crash reports can be found under ``/atmosphere/crash_reports``.
      - If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here.
      - If you don't include a crash report in instances of crash related issues, we will ask you one to provide one.
  validations:
    required: false
- type: textarea
  attributes:
    label: System Firmware Version
    description: |
      Replace X's with system firmware version at time of crash.
      You can find your firmware version in the Settings -> System, under "System Update".
      If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode.
    placeholder: X.X.X
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment?
    value: |
      - What bootloader (fusée, hekate, etc) was Atmosphère launched by: 
      - Official release or unofficial build: 
        - If using an unofficial build, include details on where/how you acquired the build: 
      - Do you have additional kips or sysmodules you're loading: 
      - Homebrew software installed: 
      - EmuMMC or SysMMC: 
        - If using an EmuMMC, include whether it's partition-based or file-based: 
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context?
    value: |
      - Additional info about your environment: 
      - Any other information relevant to your issue: 
  validations:
    required: false
