/*
 * Copyright (c) Atmosphère-NX
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

constexpr const u8 T210SdevEmcDvfsTableS6gb01[] = {
    #embed "../../mtc_tables/combined/T210SdevEmcDvfsTableS6gb01/table.bin"
};

constexpr const u8 T210SdevEmcDvfsTableH4gb01[] = {
    #embed "../../mtc_tables/combined/T210SdevEmcDvfsTableH4gb01/table.bin"
};

constexpr const u8 T210SdevEmcDvfsTableS4gb01[] = {
    #embed "../../mtc_tables/combined/T210SdevEmcDvfsTableS4gb01/table.bin"
};

