include $(ATMOSPHERE_ARCH_MAKE_DIR)/base_rules

export ATMOSPHERE_DEFINES  += -DATMOSPHERE_ARCH_X64
export ATMOSPHERE_SETTINGS +=
export ATMOSPHERE_CFLAGS   +=
export ATMOSPHERE_CXXFLAGS +=
export ATMOSPHERE_ASFLAGS  +=
