/*
 * Copyright (c) Atmosphère-NX
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

constexpr inline const u8 SdramParamsErista0_1[0x3CB] = {
    #embed "../../sdram_params/lz/sdram_params_erista_0_1.lz4"
};

constexpr inline const u8 * const SdramParamsErista0 = SdramParamsErista0_1;
constexpr inline const size_t SdramParamsSizeErista0 = sizeof(SdramParamsErista0_1);

constexpr inline const u8 * const SdramParamsErista1 = SdramParamsErista0_1;
constexpr inline const size_t SdramParamsSizeErista1 = sizeof(SdramParamsErista0_1);

constexpr inline const u8 SdramParamsErista2_3[0x3C7] = {
    #embed "../../sdram_params/lz/sdram_params_erista_2_3.lz4"
};

constexpr inline const u8 * const SdramParamsErista2 = SdramParamsErista2_3;
constexpr inline const size_t SdramParamsSizeErista2 = sizeof(SdramParamsErista2_3);

constexpr inline const u8 * const SdramParamsErista3 = SdramParamsErista2_3;
constexpr inline const size_t SdramParamsSizeErista3 = sizeof(SdramParamsErista2_3);

constexpr inline const u8 SdramParamsErista4_5[0x418] = {
    #embed "../../sdram_params/lz/sdram_params_erista_4_5.lz4"
};

constexpr inline const u8 * const SdramParamsErista4 = SdramParamsErista4_5;
constexpr inline const size_t SdramParamsSizeErista4 = sizeof(SdramParamsErista4_5);

constexpr inline const u8 * const SdramParamsErista5 = SdramParamsErista4_5;
constexpr inline const size_t SdramParamsSizeErista5 = sizeof(SdramParamsErista4_5);

constexpr inline const u8 SdramParamsErista6_7[0x3BD] = {
    #embed "../../sdram_params/lz/sdram_params_erista_6_7.lz4"
};

constexpr inline const u8 * const SdramParamsErista6 = SdramParamsErista6_7;
constexpr inline const size_t SdramParamsSizeErista6 = sizeof(SdramParamsErista6_7);

constexpr inline const u8 * const SdramParamsErista7 = SdramParamsErista6_7;
constexpr inline const size_t SdramParamsSizeErista7 = sizeof(SdramParamsErista6_7);

constexpr inline const u8 SdramParamsMariko0_1[0x3EE] = {
    #embed "../../sdram_params/lz/sdram_params_mariko_0_1.lz4"
};

constexpr inline const u8 * const SdramParamsMariko0 = SdramParamsMariko0_1;
constexpr inline const size_t SdramParamsSizeMariko0 = sizeof(SdramParamsMariko0_1);

constexpr inline const u8 * const SdramParamsMariko1 = SdramParamsMariko0_1;
constexpr inline const size_t SdramParamsSizeMariko1 = sizeof(SdramParamsMariko0_1);

constexpr inline const u8 SdramParamsMariko2_3[0x449] = {
    #embed "../../sdram_params/lz/sdram_params_mariko_2_3.lz4"
};

constexpr inline const u8 * const SdramParamsMariko2 = SdramParamsMariko2_3;
constexpr inline const size_t SdramParamsSizeMariko2 = sizeof(SdramParamsMariko2_3);

constexpr inline const u8 * const SdramParamsMariko3 = SdramParamsMariko2_3;
constexpr inline const size_t SdramParamsSizeMariko3 = sizeof(SdramParamsMariko2_3);

constexpr inline const u8 SdramParamsMariko4_5[0x3F7] = {
    #embed "../../sdram_params/lz/sdram_params_mariko_4_5.lz4"
};

constexpr inline const u8 * const SdramParamsMariko4 = SdramParamsMariko4_5;
constexpr inline const size_t SdramParamsSizeMariko4 = sizeof(SdramParamsMariko4_5);

constexpr inline const u8 * const SdramParamsMariko5 = SdramParamsMariko4_5;
constexpr inline const size_t SdramParamsSizeMariko5 = sizeof(SdramParamsMariko4_5);

constexpr inline const u8 SdramParamsMariko6_7[0x427] = {
    #embed "../../sdram_params/lz/sdram_params_mariko_6_7.lz4"
};

constexpr inline const u8 * const SdramParamsMariko6 = SdramParamsMariko6_7;
constexpr inline const size_t SdramParamsSizeMariko6 = sizeof(SdramParamsMariko6_7);

constexpr inline const u8 * const SdramParamsMariko7 = SdramParamsMariko6_7;
constexpr inline const size_t SdramParamsSizeMariko7 = sizeof(SdramParamsMariko6_7);

constexpr inline const u8 SdramParamsMariko8_9[0x428] = {
    #embed "../../sdram_params/lz/sdram_params_mariko_8_9.lz4"
};

constexpr inline const u8 * const SdramParamsMariko8 = SdramParamsMariko8_9;
constexpr inline const size_t SdramParamsSizeMariko8 = sizeof(SdramParamsMariko8_9);

constexpr inline const u8 * const SdramParamsMariko9 = SdramParamsMariko8_9;
constexpr inline const size_t SdramParamsSizeMariko9 = sizeof(SdramParamsMariko8_9);

constexpr inline const u8 SdramParamsMariko10_11[0x3D2] = {
    #embed "../../sdram_params/lz/sdram_params_mariko_10_11.lz4"
};

constexpr inline const u8 * const SdramParamsMariko10 = SdramParamsMariko10_11;
constexpr inline const size_t SdramParamsSizeMariko10 = sizeof(SdramParamsMariko10_11);

constexpr inline const u8 * const SdramParamsMariko11 = SdramParamsMariko10_11;
constexpr inline const size_t SdramParamsSizeMariko11 = sizeof(SdramParamsMariko10_11);

constexpr inline const u8 SdramParamsMariko12_13[0x3C2] = {
    #embed "../../sdram_params/lz/sdram_params_mariko_12_13.lz4"
};

constexpr inline const u8 * const SdramParamsMariko12 = SdramParamsMariko12_13;
constexpr inline const size_t SdramParamsSizeMariko12 = sizeof(SdramParamsMariko12_13);

constexpr inline const u8 * const SdramParamsMariko13 = SdramParamsMariko12_13;
constexpr inline const size_t SdramParamsSizeMariko13 = sizeof(SdramParamsMariko12_13);

