name: Build Atmosphere

on:
  push:
    branches:
      - evaron-master
    paths-ignore:
      - 'Dockerfile'
    # tags:
    #   - '[0-9]+.[0-9]+.[0-9]+'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/devkita64-atmosphere:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Atmosphere
        run: |
          source /opt/venv/bin/activate
          git config --global --add safe.directory "*"
          make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: atmosphere-artifacts
          path: ./out/nintendo_nx_arm64_armv8a/release/*
