name: Build Atmosphere

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'Dockerfile'

defaults:
  run:
    shell: bash

jobs:
  build-workflow:
    uses: ./.github/workflows/build-jobs.yaml
