name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-workflow:
    uses: ./.github/workflows/build-jobs.yaml
  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: atmosphere-artifacts
          path: "./"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "atmosphere-*.zip,fusee.bin"
          prerelease: false
          name: "Atmosphère ${{ github.ref_name }}"
