name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/devkita64-atmosphere:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Atmosphere
        run: |
          source /opt/venv/bin/activate
          git config --global --add safe.directory "*"
          make
      - name: Remove debug
        run: rm ./out/nintendo_nx_arm64_armv8a/release/atmosphere-*-debug.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: atmosphere-artifacts
          path: ./out/nintendo_nx_arm64_armv8a/release/*

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: atmosphere-artifacts
          path: "./"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "atmosphere-*.zip,fusee.bin"
          prerelease: false
          name: "Atmosphère ${{ github.ref_name }}"
